version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: api-hufghani
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=${SERVICES- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
