service: api-hufghani

frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}
  region: eu-west-2
  environment:
    API_KEY: ${ssm:/github_api_key}
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager
  - serverless-localstack

custom:
  apiGatewayCaching:
    enabled: true
  customDomain:
    domainName: api.hufghani.dev
    stage: ${opt:stage, self:custom.defaultStage}
    certificateName: hufghani.dev
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
  defaultStage: local
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: false
    docker:
      sudo: False

functions:
  githubContributions:
    handler: app/handler.githubContributions
    events:
      - http:
          path: github/contributions
          method: get
          cors: true

  githubRepositories:
    handler: app/handler.githubRepositories
    events:
      - http:
          path: github/repositories
          method: get
          cors: true
