service: api-hufghani

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    API_KEY: ${ssm:/github_api_key~true}
  apiGateway:
    shouldStartNameWithService: true
  stage: production
plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  githubProjectRepos:
    handler: app/handler.githubProjectRepos
    events:
      - httpApi:
          path: githubProjectRepos
          method: get
