service: api-hufghani

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: production
  environment:
    API_KEY: ${ssm:/github_api_key~true}
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-api-gateway-caching

custom:
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: true

functions:
  githubProjectRepos:
    handler: app/handler.githubProjectRepos
    events:
      - http:
          path: githubrepos
          method: get
          cors: true
          caching:
            enabled: true
