service: api-hufghani

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: production
  environment:
    API_KEY: ${ssm:/github_api_key~true}
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-api-gateway-caching
  - serverless-domain-manager

custom:
  apiGatewayCaching:
    enabled: true
  customDomain:
    domainName: api.hufghani.dev
    certificateName: hufghani.dev
    createRoute53Record: false
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

functions:
  github:
    handler: app/handler.github
    events:
      - http:
          path: github
          method: get
          cors: true
          caching:
            enabled: true
